menu:
  Home: /
  Archives: /archives
  About: /about

widgets:
- search

cover:
  enable: true
  url: http://selveskii.me/static/background.jpg

excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: false
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

rss:

social:
  github: https://github.com/notcome
  weibo: http://weibo.com/notcome
  google_plus:

auto_change:
  enable: false

comment:
  enable: false
